Using Python to solve systems of linear equations
* Use NumPy - linear algebra to find the solution of linear equations
* perform row reduction to bring matrix into row echleon form
* Find the solution for the system of linear equations using row reduced matrix
* Evaluate the determinant of the matrix to see again the connection between matrix singularity and the number of solutions of the linear system.

In [1]:
import numpy as np

## 1. Representing and solving a system of linear equations using matrics
1.1. System of linear equations:
$$\begin{cases} 
4x_1-3x_2+x_3=-10, \\ 2x_1+x_2+3x_3=0, \\ -x_1+2x_2-5x_3=17, \end{cases}\tag{1}$$

1.2. Solving system of Linear equations using Matrices
solve the linear system using `numpy`

In [2]:
A = np.array([
    [4,-3,1],
    [2,1,3],
    [-1,2,-5]
], dtype=np.dtype(float))

b = np.array([-10,0,17], dtype=np.dtype(float))

print(A)
print(b)

[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]
[-10.   0.  17.]


In [3]:
np.shape(A), np.shape(b)

((3, 3), (3,))

In [4]:
x = np.linalg.solve(A,b)
x

array([ 1.,  4., -2.])

1.3. Evaluation the determinant of the matrix
* Matrix A corresponding to the linear systems(1) is a square matrix. 
* A linear system containing three equations with three unknown variables will have one solution if and only if the matrix A has non-zero determinanat.

In [5]:
d= np.linalg.det(A)
d

-60.000000000000036

## 2. Solving system of Linear Equations using Row Reduction
2.1- Preparation for Row Reduction

In [6]:
b.reshape(3,1)

array([[-10.],
       [  0.],
       [ 17.]])

In [7]:
A_system = np.hstack((A, b.reshape((3,1))))
A_system

array([[  4.,  -3.,   1., -10.],
       [  2.,   1.,   3.,   0.],
       [ -1.,   2.,  -5.,  17.]])

2.2. Functions for Elementry Op


In [ ]:
def MultiplyRow(M, row_num, row_num_multiple):
    # .copy() function is required here to keep the original matrix without any changes
    M_new = M.copy()
    M_new[row_num] = M_new[row_num] * row_num_multiple
    return M_new

def AddRows(M, row_num_1, row_num_2, row_num_1_multiple):
    M_new = M.copy()
    M_new[row_num_2] = row_num_1_multiple * M_new[row_num_1] + M_new[row_num_2]
    return M_new

def SwapRows(M, row_num_1, row_num_2):
    M_new = M.copy()
    M_new[[row_num_1, row_num_2]] = M_new[[row_num_2, row_num_1]]
    return M_new

## 3. System of Linear Equations with No solutions

$$\begin{cases} 
x_1+x_2+x_3=2, \\ x_2-3x_3=1, \\ 2x_1+x_2+5x_3=0, \end{cases}\tag{2}$$


In [9]:
A_2 = np.array([
    [1,1,1],
    [0,1,-3],
    [2,1,5]
], dtype= np.dtype(float))

b_2 = np.array([2,1,0], dtype=np.dtype(float))

#Calculating Determinant
d_2 = np.linalg.det(A_2)

d_2

0.0

det is 0, thus the system cannot have one unique solution. it will have either infinitely many solutions or none. The consistency of it will depend on the free coefficients.
(right side coefficients). 

In [10]:
x_2 = np.linalg.solve(A_2, b_2)

LinAlgError: Singular matrix

You can check the system for consistency using rank. For now we can perform elementary operations to see that this particular system has no solutions

In [11]:
A_2_system = np.hstack((A_2,b_2.reshape((3,1))))
A_2_system

array([[ 1.,  1.,  1.,  2.],
       [ 0.,  1., -3.,  1.],
       [ 2.,  1.,  5.,  0.]])

In [13]:
A_2_ref = AddRows(A_2_system, 0,2, -2)
print(A_2_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0. -1.  3. -4.]]


In [14]:
A_2_ref = AddRows(A_2_ref,1,2,1)
A_2_ref

array([[ 1.,  1.,  1.,  2.],
       [ 0.,  1., -3.,  1.],
       [ 0.,  0.,  0., -3.]])