### Transpose

In [1]:
import numpy as np

In [ ]:
x = np.array([1, 2, 3])  #Transposing a regular 1-D array has no effect
x, x.shape 

(array([1, 2, 3]), (3,))

In [ ]:
y = np.array([[1,2,3]]) # but it does we use nested "matrix-style" brackets
y.shape

(1, 3)

In [ ]:
y.T, 

array([[1],
       [2],
       [3]])

In [6]:
y.T.shape

(3, 1)

* **Norms** are functions that quantify vector magnitude

In [7]:
x

array([1, 2, 3])

In [8]:
np.linalg.norm(x)

3.7416573867739413

* Special case of vector where its length is equal to one.
* Technically, **x** is a unit vector with "unit norm", i.e: ||**x**|| = 1

L1 norm 

In [9]:
x

array([1, 2, 3])

In [10]:
np.abs(1) + np.abs(2) + np.abs(3)

6

Squared L2 Norm

In [11]:
x

array([1, 2, 3])

In [12]:
(1**2 + 2**2 + 3**2)

14

In [13]:
np.dot(x,x)

14

Max Norm: ||x|| = max(Xi)
* Returns the absolute value of the largest-magnitude element

In [14]:
np.max([np.abs(1), np.abs(2), np.abs(3)])

3

### Basis Vectors
* Can be scaled to represent any vector in a given vector space.
* Typically use unit vector along axes of vector space.

Orthogonal Vectors


In [16]:
i = np.array([1,0])
j = np.array([0,1])

np.dot(i,j)

0

In [18]:
import torch

In [19]:
X = torch.tensor([[2,3], [4,5], [2,7]])
X

tensor([[2, 3],
        [4, 5],
        [2, 7]])

In [20]:
X.shape

torch.Size([3, 2])

In [25]:
X[1,:]

tensor([4, 5])

### Higher-Rank Tensor

In [26]:
img = torch.zeros([32, 28, 28, 3])
img

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.

In [29]:
V = np.array([[25,2, -3, -23]])
V, V.shape

(array([[ 25,   2,  -3, -23]]), (1, 4))

In [31]:
V.T, V.T.shape

(array([[ 25],
        [  2],
        [ -3],
        [-23]]),
 (4, 1))

In [ ]:
Y = np.array([[42, 4, 7, 99], 
              [-99, -3, 17, 22]])
Y.shape  #dimension

(2, 4)

In [33]:
Y[1,2:3]

array([17])